### ISSUE TITLE
No secureboot.js in firefox. Installed via "Load temporary Addon" feature

### ISSUE THREAD

**Issue by Abhinav1217** [meganz/web-extension#11]
I cloned the repo, and made sure that submodule is fetched and updated. 

Then as per the instructions on your readme, I went to `about:debugging#/runtime/this-firefox` and selected `manifest.json` file in `Load temporary Add-On` picker menu.  

All I get is a white screen. Looking at network tab and comparing to my other laptop where older AMO version is still working, I think `secureboot.js` is not loading properly.  

### Am I missing some configuration step? 

I tried asking on reddit but the support just downvoted my post and gave me a generic reply, even though I clearly mentioned that I am trying to install it via github not AMO.

**Comment by diegocr** [comment]
@Abhinav1217 Sorry to hear about your bad Reddit experience.

Try opening the index.html file and replace `src="/secureboot.js"` by `src="secureboot.js"`

We do have a `onBeforeRequest()` handler that should take care of the redirection, but either that stopped working recently or perhaps you changed the version tag at the manifest file which is required for that to take action.

Also, if some resource files does fail to load you may need to open the web-console and enter `localStorage.useBootStaticPath=1;location.reload()`

(re-posted from https://github.com/meganz/webclient/issues/97#issuecomment-1364531507, we can leave the discussion here if you do still find problems)

**Comment by Abhinav1217** [comment]
> perhaps you changed the version tag at the manifest file which is required for that to take action.

Nop, Nothing changed by me, Just did a git clone, then ran `git submodule update --remote --merge`, opened the debugging section of firefox and selected manifest.js to load as addon.

> Try opening the index.html file and replace src="/secureboot.js" by src="secureboot.js"

This moved something... Now I am getting an alertbox saying `lang/en.json` is missing. But atleast the secure.js is now loading. 

![Screenshot from 2022-12-25 13-28-02](https://user-images.githubusercontent.com/740584/209461219-b797bfde-693c-4330-a882-e6e4cb4b05e4.png)

> Also, if some resource files does fail to load you may need to open the web-console and enter `localStorage.useBootStaticPath=1;location.reload()`


I tried this but couldn't get this to work. Here is a screencast of how I am doing it, 


[Screencast from 2022-12-25 13-32-02.webm](https://user-images.githubusercontent.com/740584/209461259-ffb40849-e60b-48ee-b8b6-524c96cc31a9.webm)

**Comment by diegocr** [comment]
https://github.com/meganz/web-extension/blob/f95113a0f619018514c56eb511293a5fac02b64c/mega.js#L109

The `onBeforeRequest()` handler should also take care of redirecting `lang/en.json` to `lang/en_prod.json`, you can rename it manually for the time being, i'll try to look into this soon.

**Comment by Abhinav1217** [comment]
Yup It did the trick. 

I duplicated the file `cd ~/Projects/web-extension/webclient/lang` then `cp en_prod.json en.json` and it worked. 

I guess `onBeforeRequest()` is not working properly for firefox when installing from source.  

Hope things things get resolved with AMO soon.
**Thanks for all the help.**

**Comment by Abhinav1217** [comment]
Reopening as it would be better for you to decide if you want to close this now, or when issue with redirect handler is resolved for everyone.

**Comment by sundowndev** [comment]
I have the exact same issue and the trick above did not solved it.

**Comment by sundowndev** [comment]
I had the exact same issue and I had to replace the path to secureboot.js in index.html

```diff
diff --git a/index.html b/index.html
index 4734c9580..1db46de60 100755
--- a/index.html
+++ b/index.html
@@ -11,7 +11,7 @@
 <meta name="apple-itunes-app" content="app-id=706857885"/>
 </head>
 <body id="bodyel" class="theme-light not-logged">
-<script type="text/javascript" src="/secureboot.js" charset="utf-8"></script>
+<script type="text/javascript" src="/webclient/secureboot.js" charset="utf-8"></script>
```

Then run `git submodule update --remote --merge` to update the webclient.

Then `cp webclient/lang/en_prod.json webclient/lang/en.json`.

Finally, reload the extension on Firefox.
